version: "3"

services:
  flask_app:
    restart: always
    build:
      context: .
    ports:
      - 80:80
    depends_on:
      - postgres_db
    env_file:
      local.env
  postgres_db:
    image: postgres:11-alpine
    restart: always
    env_file:
      local.env
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

volumes:
  postgres_data:
