openapi: "3.0.0"

info:
  title: Assignment task
  version: "1.0"
servers:
  - url: http://0.0.0.0:5000

paths:
  /post/{post_id}:
    get:
      summary: Display post
      description: Display post
      operationId: app.views.retrieve_post
      parameters:
        - $ref: '#/components/parameters/post_id'
      responses:
        '200':
          $ref: '#/components/responses/post_retrieve'

components:
  parameters:
    post_id:
      in: path
      name: post_id
      required: true
      schema:
        type: integer

  responses:
    post_retrieve:
      description: single post
      content:
        application/json:
          schema:
            $ref : '#/components/schemas/single_post'

  schemas:
    single_post:
      properties:
        id:
          type: integer
        body:
          type: string
        timestamp:
          type: string
          format: date-time
        user_id:
          type: integer