openapi: "3.0.0"

info:
  title: Assignment task
  version: "1.0"
servers:
  - url: http://0.0.0.0:5000

paths:
  /post/{post_id}:
    get:
      summary: Display post
      description: Display post
      operationId: app.views.retrieve_post
      parameters:
        - $ref: '#/components/parameters/post_id'
      responses:
        '200':
          $ref: '#/components/responses/post_retrieve'
  /signup:
    post:
      summary: User signup
      description: User signup
      operationId: app.views.user_signup
      responses:
        '200':
          $ref: '#/components/responses/post_retrieve'


components:
  parameters:
    post_id:
      in: path
      name: post_id
      required: true
      schema:
        type: integer

  requestBodies:
    user_signup:
      required: true
      content:
        application/vnd.api+json:
          schema:
            $ref: '#/components/schemas/user_signup'


  responses:
    post_retrieve:
      description: single post
      content:
        application/json:
          schema:
            $ref : '#/components/schemas/single_post'
    user:
      description: single user
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/user'

  schemas:
    single_post:
      properties:
        id:
          type: integer
        body:
          type: string
        timestamp:
          type: string
          format: date-time
        user_id:
          type: integer
    user:
      properties:
        id:
          type: integer
        username:
          type: string
        hash:
          type: text

    user_signup:
      properties:
        username:
          type: string
        password:
          type: text
      required:
        - username
        - password

