from _datetime import datetime

from alembic import op
import sqlalchemy as sa

revision = 'initial'
down_revision = None
branch_labels = None
depends_on = None



def upgrade():
    op.create_table('posts',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('body', sa.String(140), nullable=False),
                    sa.Column('timestamp', sa.DateTime, index=True, default=datetime.utcnow),
                    sa.Column('user_id', sa.Integer()),
                    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('username', sa.String(64), nullable=False),
                    sa.Column('posts', sa.String(64)),
                    sa.Column('hash', sa.Text(), nullable=False),
                    sa.PrimaryKeyConstraint('id'),
                    sa.ForeignKeyConstraint(['posts'], ['posts.id'])
    )


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('posts')
    op.drop_table('users')

    # ### end Alembic commands ###
